import React, { useState } from 'react';
import SchemeCard from './SchemeCard';
import { motion } from 'framer-motion';
import { Filter, Copy, Check, Download } from 'lucide-react';

const ResultsSection = ({ schemes, generalAdvice, t, language }) => {
    const [filter, setFilter] = useState('All');
    const [copied, setCopied] = useState(false);

    const filteredSchemes = schemes.filter(scheme => {
        if (filter === 'All') return true;
        if (filter === 'Central') return scheme.type === 'Central';
        if (filter === 'State') return scheme.type === 'State';
        return scheme.categoryTags.includes(filter);
    });

    // Extract unique categories for filter buttons
    const categories = ['All', 'Central', 'State', ...new Set(schemes.flatMap(s => s.categoryTags))].slice(0, 8);

    const handleCopy = () => {
        const text = schemes.map(s => `${s.name} (${s.type}): ${s.description}`).join('\n\n');
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handlePrint = () => {
        window.print();
    };

    const container = {
        hidden: { opacity: 0 },
        show: {
            opacity: 1,
            transition: {
                staggerChildren: 0.1
            }
        }
    };

    return (
        <div className="space-y-8 print:space-y-4">
            <div className="flex flex-col md:flex-row justify-between items-center gap-4 print:hidden">
                <motion.h2
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="text-2xl font-bold text-white flex items-center gap-2"
                >
                    {t.recommendedSchemes} <span className="text-lg font-normal text-gray-400 ml-2">({schemes.length})</span>
                </motion.h2>

                <div className="flex gap-3">
                    <motion.button
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        onClick={handlePrint}
                        className="flex items-center gap-2 text-sm font-medium text-gray-300 hover:text-white bg-white/5 hover:bg-white/10 px-4 py-2 rounded-lg transition-colors border border-white/5"
                    >
                        <Download className="w-4 h-4" />
                        {t.print}
                    </motion.button>

                    <motion.button
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        onClick={handleCopy}
                        className="flex items-center gap-2 text-sm font-medium text-gray-300 hover:text-white bg-white/5 hover:bg-white/10 px-4 py-2 rounded-lg transition-colors border border-white/5"
                    >
                        {copied ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
                        {copied ? t.copied : t.copyAll}
                    </motion.button>
                </div>
            </div>

            {/* Print Header */}
            <div className="hidden print:block text-center mb-8">
                <h1 className="text-3xl font-bold text-black mb-2">Government Scheme Recommendations</h1>
                <p className="text-gray-600">Generated by AI Scheme Advisor</p>
            </div>

            {/* Filters */}
            <motion.div
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.2 }}
                className="flex flex-wrap gap-2 print:hidden"
            >
                <div className="flex items-center gap-2 text-gray-400 mr-2">
                    <Filter className="w-4 h-4" />
                    <span className="text-sm">{t.filter}</span>
                </div>
                {categories.map(cat => (
                    <button
                        key={cat}
                        onClick={() => setFilter(cat)}
                        className={`px-3 py-1.5 rounded-full text-xs font-medium transition-all ${filter === cat
                            ? 'bg-blue-600 text-white shadow-lg shadow-blue-500/25 scale-105'
                            : 'bg-white/5 text-gray-400 hover:bg-white/10 hover:text-white border border-white/5'
                            }`}
                    >
                        {cat}
                    </button>
                ))}
            </motion.div>

            {/* Cards Grid */}
            <motion.div
                variants={container}
                initial="hidden"
                animate="show"
                className="grid grid-cols-1 md:grid-cols-2 gap-6 items-start print:grid-cols-1 print:gap-4"
            >
                {filteredSchemes.map((scheme, index) => (
                    <SchemeCard key={index} scheme={scheme} index={index} t={t} language={language} />
                ))}
            </motion.div>

            {/* General Advice */}
            {generalAdvice && generalAdvice.length > 0 && (
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    className="bg-slate-800/50 backdrop-blur-sm rounded-xl p-6 mt-8 border-l-4 border-yellow-500 border border-white/10 print:bg-white print:border-gray-300 print:text-black"
                >
                    <h3 className="text-lg font-semibold text-white mb-4 print:text-black">💡 {t.advisorNotes}</h3>
                    <ul className="space-y-2">
                        {generalAdvice.map((tip, index) => (
                            <li key={index} className="text-gray-300 text-sm flex gap-2 print:text-gray-700">
                                <span className="text-yellow-500 print:text-black">•</span> {tip}
                            </li>
                        ))}
                    </ul>
                </motion.div>
            )}
        </div>
    );
};

export default ResultsSection;
